### ISSUE TITLE
Function videojs.APIP2P.updateLeechers not work

### ISSUE THREAD

**Issue by phambanhan** [Iragne/PCDN#2]
On demo page: http://pcdn.jairagne.ovh/ it's working fine. But when I setup on local, function videojs.APIP2P.updateLeechers not work.

Please help me.

Thanks

**Comment by Iragne** [comment]
I will check 
Can you explain your error ?

**Comment by phambanhan** [comment]
I see you have a web service: 

var checkurl = "http://"+videojs.APIP2P.options.host+"/peerjs/url/"+window.btoa(url); 

Maybe you miss this?

Thanks

**Comment by Iragne** [comment]
https://github.com/Iragne/PCDN/blob/master/server/peerjs-server/lib/server.js#L14-L19

Here the code are you sure to run correclty the server ?
