### ISSUE TITLE
MP4 pseudo streaming

### ISSUE THREAD

**Issue by rolero** [Iragne/PCDN#3]
I changed the following in index.html

<source src="/videos/sample.mp4" type="video/mp4">

peer server and webserver are not on the same machine. I testing within a local network. In Firefox everything works out nice but when I open the page in Chrome 44.0.2403.157 I get the following error:

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported. vjs.MediaError {code: 4, message: "The video could not be loaded, either because the …rk failed or because the format is not supported."}

![untitled](https://cloud.githubusercontent.com/assets/2805313/9630679/2b149fb2-517c-11e5-9982-9c83a4fd1024.png)

**Comment by Iragne** [comment]
hi yes this player was test on HLS and not on other kind of media. The first purpose is to manage HLS in P2P. i think you can solve it with a native videojs player

**Comment by rolero** [comment]
I read now. Understand that what I was trying to do would never work. Thanks
