### ISSUE TITLE
Sever can only run on port 80?

### ISSUE THREAD

**Issue by rolero** [Iragne/PCDN#4]
Can it be that the client part only works if the server is running on port 80?

I was running the server on port 3000.  The initial GET and POST to server work but when it does for example: http://stream/peerjs/url/aHR0cDovL3NvbHV0aW9ucy5icmlnaHRjb3ZlLmNvbS9qd2hpc2VuYW50L2hscy9hcHBsZS9iaXBib3AvZ2VhcjMvZmlsZVNlcXVlbmNlMC50cw==

it fails. This only works when I run the server on port 80. Seems somewhere the port parameter it not parsed.

**Comment by mr-deamon** [comment]
PR https://github.com/Iragne/PCDN/pull/5 fixes this

**Comment by Iragne** [comment]
thanks
